export enum questionType {
    'Date' = 1,
    'Single Select' = 2,
    'Type Ahead' = 3,
    'Text' = 4,
    'Upload Button' = 5,
    'Textarea' = 6,
    'CheckBox' = 7,
    'Radio' = 8,
    'Multiple Select' = 9,
    'Label' = 10,
    'Button' = 11,
    'Link' = 12,
    'CommentWithAttachments' = 13,
    'Type Ahead _KeyValuePair' = 14,
    'Compound' = 15,
    'Single Select_KeyValuePair' = 16,
    'Multiple Select_KeyValuePair' = 17,
    'file upload' = 18,
    'Phone' = 19,
    'RangeBar' = 20,
    'WithLine' = 21
}
